/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgriTraceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getHarvest"
      | "getShipment"
      | "owner"
      | "recordHarvest"
      | "recordShipment"
      | "verifyHarvest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "HarvestRecorded" | "ShipmentRecorded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getHarvest", values: [string]): string;
  encodeFunctionData(functionFragment: "getShipment", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordHarvest",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordShipment",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHarvest",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getHarvest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getShipment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordHarvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordShipment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyHarvest",
    data: BytesLike
  ): Result;
}

export namespace HarvestRecordedEvent {
  export type InputTuple = [
    qrCode: string,
    dataHash: BytesLike,
    recorder: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    qrCode: string,
    dataHash: string,
    recorder: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    qrCode: string;
    dataHash: string;
    recorder: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipmentRecordedEvent {
  export type InputTuple = [
    shipmentId: string,
    dataHash: BytesLike,
    recorder: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    shipmentId: string,
    dataHash: string,
    recorder: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    shipmentId: string;
    dataHash: string;
    recorder: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgriTrace extends BaseContract {
  connect(runner?: ContractRunner | null): AgriTrace;
  waitForDeployment(): Promise<this>;

  interface: AgriTraceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getHarvest: TypedContractMethod<
    [qrCode: string],
    [
      [string, string, bigint, boolean] & {
        dataHash: string;
        recorder: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getShipment: TypedContractMethod<
    [shipmentId: string],
    [
      [string, string, bigint, boolean] & {
        dataHash: string;
        recorder: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordHarvest: TypedContractMethod<
    [qrCode: string, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  recordShipment: TypedContractMethod<
    [shipmentId: string, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyHarvest: TypedContractMethod<
    [qrCode: string, dataHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getHarvest"
  ): TypedContractMethod<
    [qrCode: string],
    [
      [string, string, bigint, boolean] & {
        dataHash: string;
        recorder: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShipment"
  ): TypedContractMethod<
    [shipmentId: string],
    [
      [string, string, bigint, boolean] & {
        dataHash: string;
        recorder: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordHarvest"
  ): TypedContractMethod<
    [qrCode: string, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordShipment"
  ): TypedContractMethod<
    [shipmentId: string, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyHarvest"
  ): TypedContractMethod<
    [qrCode: string, dataHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "HarvestRecorded"
  ): TypedContractEvent<
    HarvestRecordedEvent.InputTuple,
    HarvestRecordedEvent.OutputTuple,
    HarvestRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ShipmentRecorded"
  ): TypedContractEvent<
    ShipmentRecordedEvent.InputTuple,
    ShipmentRecordedEvent.OutputTuple,
    ShipmentRecordedEvent.OutputObject
  >;

  filters: {
    "HarvestRecorded(string,bytes32,address,uint256)": TypedContractEvent<
      HarvestRecordedEvent.InputTuple,
      HarvestRecordedEvent.OutputTuple,
      HarvestRecordedEvent.OutputObject
    >;
    HarvestRecorded: TypedContractEvent<
      HarvestRecordedEvent.InputTuple,
      HarvestRecordedEvent.OutputTuple,
      HarvestRecordedEvent.OutputObject
    >;

    "ShipmentRecorded(string,bytes32,address,uint256)": TypedContractEvent<
      ShipmentRecordedEvent.InputTuple,
      ShipmentRecordedEvent.OutputTuple,
      ShipmentRecordedEvent.OutputObject
    >;
    ShipmentRecorded: TypedContractEvent<
      ShipmentRecordedEvent.InputTuple,
      ShipmentRecordedEvent.OutputTuple,
      ShipmentRecordedEvent.OutputObject
    >;
  };
}
